# Generated by Django 4.2.4 on 2023-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invaite_code',
            field=models.CharField(default=None, max_length=6, verbose_name='invite code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verify_code',
            field=models.CharField(default=None, max_length=4, verbose_name='verify code'),
        ),
    ]
